name: CI-pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  APP_NAME: bikepackmap
  WEBAPP_RESOURCE_GROUP: la_learning
  FULL_IMAGE_NAME: laappacr.azurecr.io/bikepackmap:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: laappacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Verify Buildx setup
        run: docker buildx ls

      - name: Build and push Docker image
        run: |
          docker build \
            --tag laappacr.azurecr.io/bikepackmap:latest \
            --tag $FULL_IMAGE_NAME \
            --push .

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: laappacr.azurecr.io/bikepackmap:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Run unit tests
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}    
          SECRET_KEY: ${{ secrets.SECRET_KEY }}    
        run: python -m unittest discover

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: production
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      - name: Restart Web App
        run: |
          az webapp config container set --name "$APP_NAME" --resource-group "$WEBAPP_RESOURCE_GROUP" --docker-image-name "$FULL_IMAGE_NAME"
          az webapp restart --name "$APP_NAME" --resource-group "$WEBAPP_RESOURCE_GROUP"