# This is a basic workflow to help you get started with Actions

name: CI-pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # build and test
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: laappacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t laappacr.azurecr.io/bikepackmap:latest .
          az acr repository tag -n laappacr.azurecr.io --repository bikepackmap --image latest --new previous-latest
          docker push laappacr.azurecr.io/bikepackmap:latest
      
      - name: Run unit tests
        env:
          REDIS_HOST: ${{ secrets.REDIS_HOST }}    
          REDIS_KEY: ${{ secrets.REDIS_KEY }}    
          SECRET_KEY: ${{ secrets.SECRET_KEY }}    
        run: docker run --rm laappacr.azurecr.io/bikepackmap:latest python -m unittest discover

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Restart Web App
        run: |
          az webapp restart --name bikepackmap --resource-group la_learning