name: CI-pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: laappacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Build and push Docker image
        run: |
          docker build \
            -t laappacr.azurecr.io/bikepackmap:latest \
            -t laappacr.azurecr.io/bikepackmap:${{ github.sha }} .
          docker push laappacr.azurecr.io/bikepackmap:latest
          docker push laappacr.azurecr.io/bikepackmap:${{ github.sha }}

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: laappacr.azurecr.io/bikepackmap:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Run unit tests
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}    
          SECRET_KEY: ${{ secrets.SECRET_KEY }}    
        run: python -m unittest discover

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      - name: Restart Web App
        run: |
          az webapp restart --name bikepackmap --resource-group la_learning